config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#home'
  get "home", to:"products#home"
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  scope :from_usa, -> { where(country_of_origin: "United States of America")}
  # "United States of America" is due to faker input
  scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
    )}

  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :price, presence: true
  validates :price, numericality: true
  validates :country_of_origin, presence: true

  before_save(:titleize_product)

  private
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :content_body, length: { in: 50..250 }
  validates :rating, presence: true
  validates :rating, :numericality => { greater_than_or_equal_to: 1, less_than_or_equal_to: 5  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :only => [:new, :edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      flash[:alert] = "oops, we have an error. Let's try that again."
      render :new
    end
  end
  
  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      flash[:alert] = "oops, we have an error. Let's try that again."
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def home
    @products = Product.all
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :country_of_origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :edit, :destroy]

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review successfully added!"
      redirect_to product_path(@product)
    else
      flash[:alert] = "oops, we have an error. Let's try that again."
      render :new
    end
  end

  def show
    @product =Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      @product = Product.find(params[:product_id])
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end

private
  def review_params
    params.require(:review).permit(:rating, :author, :content_body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Whoops! Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="container">
  <h1>WARIO'S WARES!</h1>
  <%= image_tag "marketplace2.jpg" %>
  <nav class = "navbar navbar-light bg-light">
    <div class="navbar-header">
      <%= link_to "home", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "all products", products_path%> </li>
      <% if is_admin?%>
        <li><%= link_to "add product", new_product_path%> </li>
      <%end %>
      <li> <a href="https://pangtodd.github.io/PizzaParlor/">Mario's Hideout Pizza</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "#{current_user.email}: sign out", destroy_user_session_path, method: :delete%> </li>
      <% else%>
        <li><%= link_to "sign up", new_user_registration_path%> </li>
        <li><%= link_to "sign in", new_user_session_path%> </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object=> @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang ="en">
  <head>
    <title>Wario's Wares</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>

    <section class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
    </section>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render "layouts/product_form" %>

app/views/products/home.html.erb
<h1>Welcome to <s>Mario's Market!</s> Wario's Wares</h1>

<p><s>For over 30 years, Mario's has been a proud member of the Tri-state area community! In addition to serving <a href="https://pangtodd.github.io/PizzaParlor/">the best Pizza</a> in the area, we are also the go-to spot for hard-to-find items! Please view our products below, and feel free to leave a review.</s></p>
<br>
<p>Don't like our prices? Good luck finidng it somewhere else!</p>

<% if @products.any? %>

  <h3>Spotlight! our most reviewed product:
    <% @products.most_reviews.each do |product| %>
      <%= link_to product.name, product_path(product) %></h3>
    <% end %>
  
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
    new additions
  </button>

  <div class="collapse" id="collapse1">
    <ul>
      <% @products.three_most_recent.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  </div>
  <br>
  <br>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
    Proudly made in the USA!
  </button>
  <div class="collapse" id="collapse2">
    <ul>
      <% @products.from_usa.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  </div>
  <br>
  <br>
  <a class = "btn btn-primary" href='/products' role="button">All products</a>

<% else %>
  <p>Hold your horses, we're still stocking the shelves!</p>
<% end %>
<br>
<br>
 <a class = "btn btn-primary" href='/products/new' role="button">Enter new product</a>

app/views/products/index.html.erb
<h1>Products</h1>
<%= image_tag "product.jpeg" %>

<p>Only the finest for our customers!</p>

<% if @products.any? %>
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    All products
  </button>

  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <ul>
        <% @products.each do |product| %>
          <li><%= link_to product.name, product_path(product) %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <p>Hold your horses, we're still stocking the shelves!</p>
<% end %>
<br>
<br>
<p><%= link_to "Enter new product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "layouts/product_form"%>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>Price: $<%= @product.price %></p>
<p>Country of origin: <%= @product.country_of_origin%></p>

<% if @product.reviews.any? %>
  <h4>Reviews for this product:</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to "#{review.rating} stars, review by #{review.author}", product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews are listed for this product.</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>

<p><%= link_to "Edit", edit_product_path(@product) %></p>
<p><%= link_to "Delete", product_path(@product),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/edit.html.erb
<h1>Edit review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>Add a new review:</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Product: <%= @product.name %></h1>
<h2><%= @review.rating %> out of 5 stars</h2>
<h3><%= @review.content_body %></h3>

<p><%= link_to "Edit review", edit_product_review_path(@product, @review) %></p>
<p><%= link_to "Delete review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to product", product_path(@product) %></p>